{
  imports = [
    ./minecraft.nix
    ./vaultwarden.nix
    ./unifi
    ./home-assistant.nix
    ./misc-containers.nix
    ./plausible.nix
    ./traefik.nix
    ./uptime-kuma.nix
    ./immich.nix
    ./backups.nix
    ./jellyfin.nix
    ./beszel.nix
    ./grafana.nix
    ./matrix.nix
    ./librenms.nix
    ./akvorado
    ./authentik.nix
    ./llama-swap
    ./zipline.nix
  ];
}
